### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by baileypierson** [KeventhPlace/CA_python#2]
### Criteria 1: Matplotlib and CSV
Score Level: 4/4
Comment(s): Data loaded properly!

### Criteria 2: Implementation of 2D Visualization
Score Level: 3.5/4
Comment(s): The 2D grid appears, but there is no labels on stars.

### Criteria 3: Implementation of 3D Visualization
Score Level: 3.5/4
Comment(s): The 3D grid appears, but there is no labels on stars.
Overall Score: 11/12

Solid work! Next steps would be to include labels for each star included, and to put bit more though into the readability of your code (see my other opened issues)

**Comment by KeventhPlace** [comment]
Great, thank you for the review @baileypierson
